services:
  postgres:
    ports:
      - "5432:5432"

  chat-orchestrator:
    environment:
      RAG_ENGINE_URL: http://host.docker.internal:18080

  web-service:
    environment:
      RAG_ENGINE_URL: http://host.docker.internal:18080
